# Generated by Django 4.1.3 on 2023-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_item_m_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='m_photo',
            field=models.ImageField(default='me', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
