# Generated by Django 4.1.3 on 2023-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='df', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='df', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='dfg', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='rgt', upload_to='photos'),
            preserve_default=False,
        ),
    ]
