# Generated by Django 4.1.3 on 2023-01-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_item_image1_item_image2_item_image3_item_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='crated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
