# Generated by Django 4.1.3 on 2023-01-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_addres',
            new_name='apartment_address',
        ),
    ]
