# Generated by Django 4.1.3 on 2023-02-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_amoutn_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, choices=[('AD', 'Adidas'), ('AS', 'Asics'), ('CB', 'Canterbury'), ('CV', 'Converse'), ('NK', 'Nike'), ('ML', 'Millet'), ('PM', 'Puma'), ('RB', 'Reebok'), ('UA', 'Under Armour')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('AD', 'Adidas'), ('AS', 'Asics'), ('CB', 'Canterbury'), ('CV', 'Converse'), ('NK', 'Nike'), ('ML', 'Millet'), ('PM', 'Puma'), ('RB', 'Reebok'), ('UA', 'Under Armour')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('W', 'Women'), ('C', 'Children')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SP', 'Sport Wears'), ('TS', 'T Shirts'), ('OW', 'Out Wears'), ('SH', 'Shoes'), ('PT', 'Pants')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
